version: '3'
services: 
  seedbox: 
    image: dperson/transmission
    volumes: 
      - /data/downloads/Downloads:/var/lib/transmission-daemon/downloads
      - /data/downloads/Incomplete:/var/lib/transmission-daemon/incomplete 
    environment: 
      - TRUSER=$seedbox_user
      - TRPASSWD=$seedbox_password




